### ISSUE TITLE
Incorrect NVDA Bot responses: "Navigate to the bottom of a modal dialog" (Modal Dialog Example, Test 14.1, V24.05.09)

### ISSUE THREAD

**Issue by IsaDC** [w3c/aria-at#1070]
## Description of Behavior

I still getting the results from the previous NVDA version.

## Test Setup

- Test File: [test-14-navToEndModalDialog-nvda.collected.html](https://aria-at.netlify.app/tests/modal-dialog/test-14-navToEndModalDialog-nvda.collected.html)
- AT: NVDA (Version 2024.1)
- Browser: Chrome (Version 124)

**Comment by IsaDC** [comment]
Now I get this when trying to re-run the test plan:
* AT: NVDA 2023.3.3
* Browser: Chrome 99
There are no results to evaluate.
I have already tried signing out and back in and performing a hard refresh, but the issue persists.

Cc @jugglinmike

**Comment by IsaDC** [comment]
Then, when I finally get some results, they don't match with the manual results. E.G.
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/loque/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<link rel=themeData
href="file:///C:/Users/loque/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/loque/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-GB style='tab-interval:36.0pt;word-wrap:break-word'>



Test | Bot Results | Manual   Results
-- | -- | --
Test   6:Navigate to the bottom of a modal dialog | A blank line | button    Verify Address  button      Add  button    Cancel
Test 8:Bump   into the top edge of a modal dialog | A blank line | heading    level 2    Add Delivery Address



<p class=MsoNormal><o:p>&nbsp;</o:p></p>


</body>

</html>

**Comment by gnarf** [comment]
I set this up for modal tests with NVDA/chrome on the staging site (which is using the same automation backend) and it responded using 2024.1, I'm not sure where the old version results were sneaking in, but all new NVDA automation runs should be 2024.1 since May 9

The "blank line" results are confusing, they don't seem related to the other keypress errors, I'll have to do some local testing to see if I can get a screen recording of it running this test.

**Comment by gnarf** [comment]
The empty results were tracked down to a problem with these tests `rowNumber` property being a decimal (`14.1` as well as `14`).

PR w3c/aria-at-app#1105 solves this issue and the fix was deployed to staging.  The results of that run are still streaming in, but show the same as your manual testing for #6 https://aria-at-staging.w3.org/run/575?user=9999

**Comment by ccanash** [comment]
Hi @IsaDC , this was released . I will close it but please let me know if anything is not working as expected
