### ISSUE TITLE
Tests within test plan need an "order"

### ISSUE THREAD

**Issue by spectranaut** [w3c/aria-at#137]
Right now, you can not order the tests within a test plan for execution. @zcorpan suggested putting the order in the filename (so it will be parsed from the file name when a test run is executed).

**Comment by zcorpan** [comment]
Removing `good first issue` label for now. This probably warrants renewed discussion that we want to make this change at this stage.

**Comment by jscholes** [comment]
@zcorpan, @spectranaut I don't understand the issue being described.  Tests will be executed in the order in which they are arranged in the CSV file, and during test writing we try to create a progression that is as logical as possible.  Is there a concrete use case for having the order be specified separately?

**Comment by zcorpan** [comment]
Nope. The issue (back when this was reported) was that the implicit order was lost because the filenames didn't encode the `testId`, and the test runner would present tests in a different order than the implicit order in the CSV. However, looking at the files now I see that they already *do* what this issue suggests, so the order is maintained. This issue just wasn't closed as fixed.

So... closing now! 🙂

**Comment by mcking65** [comment]
@zcorpan

Do we maintain the test id information in the data model and keep it in a way that it can be used to order test results in reports?
