### ISSUE TITLE
Aria AT - Reports Home Page

### ISSUE THREAD

**Issue by isaacdurazo** [w3c/aria-at#159]
## Reports
This page provides all users to access to all draft and final report data from all test cycles. It enables users to:

1.  See all reports from a given cycle. Within that cycle:
-  See reports for a given AT
-  See reports for a given browser
1.  See all reports for a given AT, perhaps across cycles?
2.  See all reports for a given browser, perhaps across cycles?
3.  See all reports for a given plan
-  etc.

We need to discuss MVP.

**Comment by isaacdurazo** [comment]
@mcking65 I got this issue started with what we have so far from your comment in https://github.com/w3c/aria-at/issues/132#issuecomment-616421203

**Comment by isaacdurazo** [comment]
## Tes Reports Page
This page is accessible to anyone and shows Test Reports in their draft and final states. It includes a table with the following columns:

  1. Test Run Cycle name
  2. AT and Browser Combination
  3. Test plan name

At the top of the table there is a filer control where the user can type what they are looking for and the table will dynamically filter the data. In addition to this feature, each column heading has a sort button.

![Test Reports](https://user-images.githubusercontent.com/1379244/80256875-87069b80-8634-11ea-9c02-a9a947f6d879.png)

**Comment by mcking65** [comment]
@isaacdurazo

Isaac, I like the simplicity.

Here are my questions/comments:
1. Is the test plan name a link that opens the report?
1. Where do I see the status of the report, e.g., draft vs final?
1. If AT and browser are in a single column, that imposes limits on future sorting and filtering.
1. What is the default sort order?
1. If I sort by pattern, then sort by AT/Browser, what will the sort order of the pattern column be? What would the order of the cycle column be?
1. How does the filter work? If there is only one filter (as opposed to a filter for each column), If I want only NVDA reports, would it then include any row that has NVDA in any of the 3 columns?

Suggestions:
1. Consider separate columns for AT and Browser.
1. Add a column for status. Also, if a report is draft, let's make that especially clear by doing something to the row or to the plan link or both. We may also want off-screen text in the link text for screen reader users that emphasizes the status.
1. Specify a default sort order. I think it should be Cycle descending, AT ascending, plan ascending, Browser ascending, status ascending. This would group everything for a given AT together first by plan then by browser. The idea here is to make the AT developer use case the most important.
1. Specify how sort works when multiple sort commands are given. Perhaps a reset sort is needed to reset to default order. Then consider the user wanting to group rows in different ways by sorting columns in different ways, e.g., show me all Chrome results together sorted first by pattern then by AT. This would require the user to first sort by AT, then by pattern, then by browser. Admitedly, this is not very intuitive, but it is logical and probably sufficient for a V1. a V1+ feature could be to add a nice multi-column sort popup.
1. For V1, consider not providing sort on cycle for V1. Just keep all rows for a cycle together and put the most recent cycle at the top.
1. For V1, consider having only two filters, one for AT and one for status. Consider making all other filters a v2 feature and providing filters for each column instead of asingle general filter.

These comments are based on the community group priority of serving the assistive technology developer audience. Our top goal is to help them improve quality. The next most important audience is web page developers.

AT devs need to be able to see data for their specific AT. We can solicit their feedback on this when we do user testing. My assumption is that enabling them to filter to show only reports for their AT and then see the data sorted first by plan then by browser makes the most sense. It would be easy enough for them to resort by browser and then plan just by sorting the browser column.

Ideally the reports page will eventually surface some high-level summary data. But, for an absolute bare-bones V1, it just needs to provide access to reports. We should, though, consider a stretch goal of providing some summary data on the reports page, e.g., a column for % required support and a column for %optional support. We might want to only fill in those columns if the data is final. For draft rows, we may want to emphasize the draft nature of the data by putting some kind of draft icon in the cell with hover/description that tells the user the data is draft and they can open the report to see the preliminary results.

**Comment by mfairchild365** [comment]
I'll echo @mcking65's comments/questions.

Some of my own thoughts:

- I'm not sure that a filter by test plan name is essential for V1. A filter for AT may be most helpful for AT developers, as it will let them quickly refine results that only pertain to them.
- Will this be paginated for v1?
- Do we want to show any sort of pass/failure information in this report? That information could help AT devs prioritize which at/browser/plans to focus on.
- I also suggest making separate columns for AT and browser
- I also suggest making separate columns for Test plan and status (which appear to be in the same column right now)

**Comment by isaacdurazo** [comment]
Thanks, @mcking65. Here the answers to your questions:

>Is the test plan name a link that opens the report?

Yes, I forgot to describe this and it's now updated in the wireframes description.

>Where do I see the status of the report, e.g., draft vs final?

I also forgot to include this part in the description, but yes, it is also there and I have them as labels next to the test plan name. It's been added to the wireframes description now.

>If AT and browser are in a single column, that imposes limits on future sorting and filtering.

That's a great point, I don't see a problem if we split these up into to, so I'll do that change.

>What is the default sort order?

I didn't consider any specific rules for this. In the wireframe I have it grouped by cycle. I think we can define that as par of the technical specs?

>If I sort by pattern, then sort by AT/Browser, what will the sort order of the pattern column be? What would the order of the cycle column be?

The way I'm thinking about this functionality is so that if you sort a column, and then you sort another one, the later overwrites what was previously sorted. If the user is looking for something more specifically, the idea is that they would use the filtering mechanism to search for that.

>How does the filter work? If there is only one filter (as opposed to a filter for each column), If I want only NVDA reports, would it then include any row that has NVDA in any of the 3 columns?

Your assumption is correct. It will filter the word in all columns.

**Comment by johnfoliot** [comment]
Longtime lurker and occasional commentor's question(s):

What about versions of software? Is your report presuming the most current/recent? With browsers updating (potentially mid-stream in the test process, and/or after test results) it seems to me that which version of OS, Browser, and Screen Reader/AT should be noted - certainly for historic reasons. (ref: CanIuse.com)

And speaking of AT, is the intention to only test the "big 4" (JAWs, NVDA, VoiceOver, Talk Back)? What about screen magnification tools with screen-readers on-board?

Thanks!

**Comment by zcorpan** [comment]
@johnfoliot see #116 for which ATs and which versions to test. As for the report, I think each report should have the following information (also see #119):

* The date the test cycle was initiated
* Maybe the date it moved to "Final"
* The versions of the software (OS, browser, AT) tested (version number, build date, release channel...)
* The git revision of the test

**Comment by isaacdurazo** [comment]
Thanks for your comments @mfairchild365 Here are the answers to your questions:

>I'm not sure that a filter by test plan name is essential for V1. A filter for AT may be most helpful for AT developers, as it will let them quickly refine results that only pertain to them.

What do you think about the "global filter" that I have? I was think this way users can filer by whatever they want instead of having a filter for a specific "topic".

>Will this be paginated for v1?

I would have to double check with the team. I'm not sure we have this within the scope

>Do we want to show any sort of pass/failure information in this report?

I agree this would be beneficial. I think we should discuss this in the CG call. I will also check with the team with regard to the scope of this implementation

**Comment by isaacdurazo** [comment]
@mcking65 I've updated the wireframe with everyone's suggestions/ideas. The only thing I'm not so sure about is having filters at the column level. I think having a global filter that considers all data within the table, gives the the user the freedom to to search whatever they might need. Instead of restricting their ability to search within the AT column, for example, they can search at a global level for anything.

**Comment by mcking65** [comment]
@johnfoliot

> What about versions of software? Is your report presuming the most current/recent? With browsers updating (potentially mid-stream in the test process, and/or after test results) it seems to me that which version of OS, Browser, and Screen Reader/AT should be noted - certainly for historic reasons. (ref: CanIuse.com)

Isaac, I was assuming that the AT column shows the AT name and version. If not, it should. Same with browser.

> And speaking of AT, is the intention to only test the "big 4" (JAWs, NVDA, VoiceOver, Talk Back)? What about screen magnification tools with screen-readers on-board?

John, The intention is to start with 3 desktop screen readers in 2020 and expand over time to cover more screen readers on more platforms and then more AT on more platforms. The decision to start with desktop platforms is based on the fact that is the only place where we have AAMs.

And, we are starting with ARIA implementations of accessibility semantics but plan to eventually cover native HTML implementations of those semantics as well. There are other opportunities to expand that dimension of scope as well over time.

We have the scope plans in a presentation about the project, but still need to update/improve/organize the project documentation in this repo.

**Comment by isaacdurazo** [comment]
I've talked to the team about the questions that came up during the last CG call with regard to some features for the reports page. Here the answers:

  1. **Include AT and Browsers version.** We will include this within the scope of this task.
  2. **Sort Cycle column in descending order by date without showing the date.** We will include this within the scope of this task.
  3. **Filtering mechanism.** The easiest thing will be to have an independent filter for each AT and status columns. If we want to change to a global filter in v2, it shouldn't be a problem
  4. **Pass/fail for final reports in status column.** We are not sure yet if it will be possible to fit this within the current scope of this task, so we'll have to wait until then, but it's likely we'll have to push this to v2

**Comment by zcorpan** [comment]
@isaacdurazo wanted a few minutes on the call to give an update on this.

**Comment by a11ydoer** [comment]
Thanks for the udpate, @isaacdurazo 

> Filtering mechanism. The easiest thing will be to have an independent filter for each AT and status columns. If we want to change to a global filter in v2, it shouldn't be a problem

In summary, the decision is sorting/filtering by columns and not by global keyword filter. I think it will be fine without global keyword filter. Global keyword filter is rathter confusing at this stage. 

>Pass/fail for final reports in status column. We are not sure yet if it will be possible to fit this within the current scope of this task, so we'll have to wait until then, but it's likely we'll have to push this to v2

I think pass/fail is the important information in this report. I wonder why it is not certain to include this to the current scope. Is it because this is rather technical challenge not UI design issue?

**Comment by isaacdurazo** [comment]
@a11ydoer so sorry for responding this late. I totally missed this comment. Here's my answer:

>I think pass/fail is the important information in this report. I wonder why it is not certain to include this to the current scope. Is it because this is rather technical - it does not return data of pass or fail? - challenge not UI design issue?

I agree with you that it is important o include this. It's not really a design issue, but that the Engineering team hasn't gotten to this yet, so they are uncertain still if they will be able to incorporate it as part of the scope of work.

**Comment by isaacdurazo** [comment]
Closing this discussion now. I will be creating new issues for new wireframe iterations
