### ISSUE TITLE
Is there a limit of 5 assertions for each test?

### ISSUE THREAD

**Issue by jongund** [w3c/aria-at#193]

**Comment by mcking65** [comment]
If I provide more than 5 assertions, the sixth and beyond are not in the test file. So, there does seem to be a limit.

@s3ththompson  this is a pretty critical issue I think we need to prioritize. See my comment in #251.

**Comment by spectranaut** [comment]
@mcking65 and @jongund -- it's the test creation script, actually, that limits the number of assertions to 5. It only takes the first 5 assertions from the spreadsheet, so the fix should be pretty simple, but it won't effect the pilot test.

[Here is the location in the test creation code](https://github.com/w3c/aria-at/blob/2a3c46f1cbd20e7f2f0a706052d2d82aaf207a29/scripts/create-tests.js#L367)

Since it can't effect the pilot -- can this be fixed by the community group?

**Comment by mfairchild365** [comment]
I'll take point on fixing this. For now, I'll just bump up the limit to something more reasonable. This being a CSV file, I'm not sure that we can ever remove a hard limit.
