### ISSUE TITLE
Feedback on runner prototype

### ISSUE THREAD

**Issue by spectranaut** [w3c/aria-at#23]
I made a prototype of the "runner" -- the goal of the runner was to be as simple as the CSS WG's test runner and to provide us the ability to test "performing a test run". The working group should eventually build something with designers, user testing and more features :) Tomorrow I'll be working on the features to show summary's of past test runs and download JSON files with test rests.

Soon I'll push the runner to gh-pages on this repo (instead of my fork) and have the runner rebuild and publish on merges into master.

[https://spectranaut.github.io/aria-at/runner/](https://spectranaut.github.io/aria-at/runner/)

You will still be able to visit any tests committed to this repository individually, exactly as they are committed under the test directory, for example:

[https://spectranaut.github.io/aria-at/tests/checkbox/read-checkbox.html](https://spectranaut.github.io/aria-at/tests/checkbox/read-checkbox.html)

**Comment by mcking65** [comment]
Valerie, looking great!!

Here are 3 simple ideas for improvement.

First, Simplify the names of the disclosure buttons. Instead of:
>Run all tests for desing pattern: checkbox
Make the name:
>tests for checkbox

Secondly, it would be nice to have a "select all" checkbox that is a tri-state at the top of the list for a pattern.
This would make it easy to check all, uncheck all, or have a partially selected state for that pattern.

Finally, change the name of the submit button to include the currently selected number of tests, e.g., "Run 8 selected tests for 1 pattern". That would be helpful confirmation of what you are about to do.

**Comment by mfairchild365** [comment]
I agree! It's looking great!

Some other thoughts:

1. how do I define my JAWS version
2. how do I define my OS version (potentially relevant if a11y APIs change)
3. what if I want to test in one browser and record results in another? Can I customize my browser and version number?

**Comment by mcking65** [comment]
@mfairchild365 commented:

> 1. how do I define my JAWS version

Good catch; we need that.

> 2. how do I define my OS version (potentially relevant if a11y APIs change)

Worth capturing. Not so important for the prototype. More important when we build a prod system.

> 3. what if I want to test in one browser and record results in another? Can I customize my browser and version number?

Also a good idea, but not so important for a prototype.
