### ISSUE TITLE
Consider using Zoom for meetings

### ISSUE THREAD

**Issue by mfairchild365** [w3c/aria-at#291]
From Hadi

> I am also wondering if the team has any objection to switch to a more accessible conferencing tool like Zoom.

**Comment by sinabahram** [comment]
Many +1's from me on this suggestion.

**Comment by robfentress** [comment]
I'm fine with Zoom.

**Comment by mcking65** [comment]
We are using BlueJeans because I have an account via Facebook and can manage the meeting. I don't have a Zoom account. W3C does not provide conferencing support for community groups.

BlueJeans is just as accessible on the iPhone as Zoom. It is possible to open BlueJeans app from a link just like Zoom, and one-touch dial is also available.

On web, it is a bit less screen reader friendly.

Are there some specific accessibility issues that you are finding particularly annoying?

**Comment by sinabahram** [comment]
When last I attempted to use BlueJeans on Windows, it was a pretty inaccessible/frustrating experience. Mobile really doesn't matter to me for these kinds of calls, as I take them in a work context e.g. at my desk, with various audio interfaces, a desk microphone and mixer setup, etc. Happy to try it again, but it would be wonderful to use Zoom for these calls if possible, especially as that would then match the ARIA WG calls as well. If PAC ends up becoming a more regular contributer/attendee, I'd be happy to use our account to host, or even to upgrade it to allow for me to assign you, @mcking65 as an authorized user. Not sure if that helps, but just some thoughts/suggestions.

**Comment by mfairchild365** [comment]
@mcking65 I have a Zoom account via Deque that we can use.

**Comment by jongund** [comment]
@mfairchild365 
Zoom is fine with me

**Comment by mfairchild365** [comment]
We will use zoom starting with the Sept 10th meeting.
