### ISSUE TITLE
Create menubar editor test in prototype

### ISSUE THREAD

**Issue by mfairchild365** [w3c/aria-at#34]
Assigned to Matt until it can be assigned to Jon and Yohta

**Comment by Yohta89** [comment]
Progress as of 1/29

**[Progress]**
1. Made [the draft list of test assertions]([200129_Menubar_test writing.xlsx](https://github.com/w3c/aria-at/files/4129631/200129_Menubar_test.writing.xlsx)) on a spreadsheet, based on Valerie's checkbox example.
To be discussed with Jon to make sure if I'm covering everything later this week.

2. Jon made a[ branch for testing.](https://github.com/w3c/aria-at/blob/menubar-edit/tests/menubar-editor/navigate-to-menubar-interaction.html)
To be tested later this week.

3. Test instruction and commands need to be added later this week.

**[Notes and clarification at the meeting]**
1. The assumption is all the assertions in the submenu are interaction mode since JAWS automatically switches to interaction mode when entering a form.
i.e. Testing tasks such as navigating to menuitemradio/menuitemcheckxbox are all written in interaction mode.

2. [In the Checkbox text,](https://github.com/w3c/aria-at/tree/master/tests/checkbox) the first two test tasks started with "Navigating through checkbox".
Does it apply to menubar assertions as well? I wanted to make sure the expected output assertion to capture aria-label="Text Formatting" in right. See Test No. 1&2 in the attached spreadsheet.

**Comment by Yohta89** [comment]
@mcking65 
We have taken the tests “activate switches mode” and “navigate switches mode” from the combobox tests.

When rewriting tests for menubar editor are we “activating” the menubar, or are we activating a menuitem in the menubar.

The menubar itself is not interactive, but its child menuitems are.

When a JAWS and NVDA screen reader are in “read” mode  their  virtual cursor seems to navigation to only the menu items and never just on the menubar container.

So are we activating a menuitem in a menubar or activating the menubar and the focus just ends up on a menuitem in the menubar?

Jon

**Comment by Yohta89** [comment]
Progress as of 2/5

[Progress]

Mostly made [the draft list of test assertions](200129_Menubar_test writing.xlsx) lists of assertions and key commands combinations on [the spreadsheet](https://uofi.box.com/s/pgfnvg0f86iprt42p084k3n8obs3xu5a).

To be tested on the branch Jon created later this week and shooting to finish it by the end of next week.

[Notes and clarification at the meeting]
[Activation questions regarding menubar editor test](https://github.com/w3c/aria-at/issues/34#issuecomment-580424379)

**Comment by Yohta89** [comment]
Progress as of 2/12

**[Progress]**
[Menubar test writing spreadsheet](https://uofi.box.com/s/fhon8xdu3vz9ush68aznwt5yer0lajd2)
- Add "Applies to" column.
- Change verb to present tense
- In the command sheet, if the multiple keystrokes are same, connect them with "or".   e.g. INS_TAB or INS_UP
- In the command sheet, Added "Roles/Property being tested" column as a key to help sheet
- In the command sheet, describe the steps to carry out testing tasks.
e.g. For Read Text Color group test, Starting with tab into the first menuitem in menubar > Move focus to Style/Color > Open submenu and move to Bold menuitem > Change to Virtual PC Cursor > Move Virtual PC cursor to the boundary of group > read current focus

**[To be updated after the meeting(To be updated later today)]**

- Change language based on the objective of AT command

**Comment by spectranaut** [comment]
Closing at the menubar editor tests have been written
