### ISSUE TITLE
Create tests for APG design pattern example: Disclosure (Show/Hide) for Navigation Menus

### ISSUE THREAD

**Issue by jscholes** [w3c/aria-at#342]
#### Applies To

* APG design pattern: [Disclosure (Show/Hide)](https://w3c.github.io/aria-practices/#disclosure)
* Specific example: [Disclosure (Show/Hide) for Navigation Menus](https://w3c.github.io/aria-practices/examples/disclosure/disclosure-navigation.html)

#### Testing Notes

This issue thread will house all documentation relating to the development of a test plan for the "Disclosure (Show/Hide) for Navigation Menus" APG example, which conforms to the "Disclosure" design pattern.  All follow-ups (including the test plan itself) will be added as new comments to facilitate notifications, but this initial comment will be updated with relevant details and URLs as needed for convenience.

#### Useful Links

* [Previewable Tests Index](https://raw.githack.com/w3c/aria-at/tests/disclosure-navigation/tests/disclosure-navigation/index.html)
* [Previewable Tests Review Page](https://raw.githack.com/w3c/aria-at/tests/disclosure-navigation/review/disclosure-navigation.html)

#### Additional References

* [button (role)](https://w3c.github.io/aria/#button)
* [region(role)](https://w3c.github.io/aria/#region)
* [aria-label(property)](https://w3c.github.io/aria/#aria-label)
* [aria-current (state)](https://w3c.github.io/aria/#aria-current)
* [aria-expanded (state)](https://w3c.github.io/aria/#aria-expanded)

**Comment by jscholes** [comment]
Keyboard behaviour consistency issue filed for this example: https://github.com/w3c/aria-practices/issues/1632

**Comment by IsaDC** [comment]
Below is the test plan for the Disclosure (Show/Hide) for Navigation Menus example.  Note that testers are not instructed to move into a dropdown of links using the Right Arrow key due to the inconsistency noted in https://github.com/w3c/aria-practices/issues/1632.

Each test title is marked up as a level 4 heading to facilitate screen reader navigation.

#### Navigate forwards to a collapsed disclosure button in reading mode

* Applies to: JAWS, NVDA
* Mode: reading
* Instructions: Navigate to the first disclosure button in the navigation region. Note: it should be in the collapsed state.
* Commands:
    * B
    * F
    * Tab
    * Down Arrow
* Setup script description: sets focus on a link before the first disclosure button

##### Assertions

|Assertion|Priority|Reference|
|---------|--------|-----|
|Role 'button' is conveyed|required|`<button>`|
|Name 'About' is conveyed|required|Visible text content contained within the `<button>` element|
|State of the button (collapsed) is conveyed|required|`aria-expanded="false"`|

#### Navigate backwards to a collapsed disclosure button in reading mode

* Applies to: JAWS, NVDA
* Mode: reading
* Instructions: Navigate to the first disclosure button in the navigation region. Note: it should be in the collapsed state.
* Commands:
    * Shift+B
    * Shift+F
    * Shift+Tab
    * Up Arrow
* Setup script description: sets focus on the second disclosure button in the navigation region

##### Assertions

|Assertion|Priority|Reference|
|---------|--------|-----|
|Role 'button' is conveyed|required|`<button>`|
|Name 'About' is conveyed|required|Visible text content contained within the `<button>` element|
|State of the button (collapsed) is conveyed|required|`aria-expanded="false"`|

#### Navigate forwards to a collapsed disclosure button in interaction mode

* Applies to: JAWS, NVDA
* Mode: interaction
* Instructions: Navigate to the first disclosure button in the navigation region. Note: it should be in the collapsed state.
* Commands:
    * Tab
* Setup script description: sets focus on a link before the first disclosure button

##### Assertions

|Assertion|Priority|Reference|
|---------|--------|-----|
|Role 'button' is conveyed|required|`<button>`|
|Name 'About' is conveyed|required|Visible text content contained within the `<button>` element|
|State of the button (collapsed) is conveyed|required|`aria-expanded="false"`|

#### Navigate backwards to a collapsed disclosure button in interaction mode

* Applies to: JAWS, NVDA
* Mode: interaction
* Instructions: Navigate to the first disclosure button in the navigation region. Note: it should be in the collapsed state.
* Commands:
    * Shift+Tab
    * Up Arrow
    * Left Arrow
    * Home
* Setup script description: sets focus on the second disclosure button in the navigation region

##### Assertions

|Assertion|Priority|Reference|
|---------|--------|-----|
|Role 'button' is conveyed|required|`<button>`|
|Name 'About' is conveyed|required|Visible text content contained within the `<button>` element|
|State of the button (collapsed) is conveyed|required|`aria-expanded="false"`|

#### Navigate forwards to a collapsed disclosure button

* Applies to: macOS VoiceOver
* Mode: interaction
* Instructions: Navigate to the first disclosure button in the navigation region. Note: it should be in the collapsed state.
* Commands:
    * Tab
    * Control+Option+Right Arrow
* Setup script description: sets focus on a link before the first disclosure button

##### Assertions

|Assertion|Priority|Reference|
|---------|--------|-----|
|Role 'button' is conveyed|required|`<button>`|
|Name 'About' is conveyed|required|Visible text content contained within the `<button>` element|
|State of the button (collapsed) is conveyed|required|`aria-expanded="false"`|

#### Navigate backwards to a collapsed disclosure button

* Applies to: macOS VoiceOver
* Mode: interaction
* Instructions: Navigate to the first disclosure button in the navigation region. Note: it should be in the collapsed state.
* Commands:
    * Shift+Tab
    * Control+Option+Left Arrow
    * Up Arrow
    * Left Arrow
    * Home
* Setup script description: sets focus on the second disclosure button in the navigation region

##### Assertions

|Assertion|Priority|Reference|
|---------|--------|-----|
|Role 'button' is conveyed|required|`<button>`|
|Name 'About' is conveyed|required|Visible text content contained within the `<button>` element|
|State of the button (collapsed) is conveyed|required|`aria-expanded="false"`|

#### Navigate forwards to an expanded disclosure button in reading mode

* Applies to: JAWS, NVDA
* Mode: reading
* Instructions: Navigate to the first disclosure button in the navigation region. Note: it should be in the expanded state.
* Commands:
    * B
    * F
    * Tab
    * Down Arrow
* Setup script description: sets focus on a link before the first disclosure button, and sets the state of the first button to expanded

##### Assertions

|Assertion|Priority|Reference|
|---------|--------|-----|
|Role 'button' is conveyed|required|`<button>`|
|Name 'About' is conveyed|required|Visible text content contained within the `<button>` element|
|State of the button (expanded) is conveyed|required|`aria-expanded="true"`|

#### Navigate backwards to an expanded disclosure button in reading mode

* Applies to: JAWS, NVDA
* Mode: reading
* Instructions: Navigate to the first disclosure button in the navigation region. Note: it should be in the expanded state.
* Commands:
    * Shift+B
    * Shift+F
    * Shift+Tab
    * Up Arrow
* Setup script description: sets focus on the second disclosure button in the navigation region, and sets the state of the first button to expanded without displaying its associated list of links

##### Assertions

|Assertion|Priority|Reference|
|---------|--------|-----|
|Role 'button' is conveyed|required|`<button>`|
|Name 'About' is conveyed|required|Visible text content contained within the `<button>` element|
|State of the button (expanded) is conveyed|required|`aria-expanded="true"`|

#### Navigate forwards to an expanded disclosure button in interaction mode

* Applies to: JAWS, NVDA
* Mode: interaction
* Instructions: Navigate to the first disclosure button in the navigation region. Note: it should be in the expanded state.
* Commands:
    * Tab
* Setup script description: sets focus on a link before the first disclosure button, and sets the state of the first button to expanded

##### Assertions

|Assertion|Priority|Reference|
|---------|--------|-----|
|Role 'button' is conveyed|required|`<button>`|
|Name 'About' is conveyed|required|Visible text content contained within the `<button>` element|
|State of the button (expanded) is conveyed|required|`aria-expanded="true"`|

#### Navigate backwards to an expanded disclosure button in interaction mode

* Applies to: JAWS, NVDA
* Mode: interaction
* Instructions: Navigate to the first disclosure button in the navigation region. Note: it should be in the expanded state.
* Commands:
    * Shift+Tab
    * Up Arrow
    * Left Arrow
    * Home
* Setup script description: sets focus on the second disclosure button in the navigation region, and sets the state of the first button to expanded without displaying its associated list of links

##### Assertions

|Assertion|Priority|Reference|
|---------|--------|-----|
|Role 'button' is conveyed|required|`<button>`|
|Name 'About' is conveyed|required|Visible text content contained within the `<button>` element|
|State of the button (expanded) is conveyed|required|`aria-expanded="true"`|

#### Navigate forwards to an expanded disclosure button

* Applies to: macOS VoiceOver
* Mode: interaction
* Instructions: Navigate to the first disclosure button in the navigation region. Note: it should be in the expanded state.
* Commands:
    * Tab
    * Control+Option+Right Arrow
* Setup script description: sets focus on a link before the first disclosure button, and sets the state of the first button to expanded

##### Assertions

|Assertion|Priority|Reference|
|---------|--------|-----|
|Role 'button' is conveyed|required|`<button>`|
|Name 'About' is conveyed|required|Visible text content contained within the `<button>` element|
|State of the button (expanded) is conveyed|required|`aria-expanded="true"`|

#### Navigate backwards to an expanded disclosure button

* Applies to: macOS VoiceOver
* Mode: interaction
* Instructions: Navigate to the first disclosure button in the navigation region. Note: it should be in the expanded state.
* Commands:
    * Shift+Tab
    * Control+Option+Left Arrow
    * Up Arrow
    * Left Arrow
    * Home
* Setup script description: sets focus on the second disclosure button in the navigation region, and sets the state of the first button to expanded without displaying its associated list of links

##### Assertions

|Assertion|Priority|Reference|
|---------|--------|-----|
|Role 'button' is conveyed|required|`<button>`|
|Name 'About' is conveyed|required|Visible text content contained within the `<button>` element|
|State of the button (expanded) is conveyed|required|`aria-expanded="true"`|

#### Read information about a collapsed disclosure button in reading mode

* Applies to: JAWS, NVDA
* Mode: reading
* Instructions: With the reading cursor on the first disclosure button in the navigation region, read information about the button.
* Commands:
    * Insert+Tab
* Setup script description: sets focus on the first disclosure button

##### Assertions

|Assertion|Priority|Reference|
|---------|--------|-----|
|Role 'button' is conveyed|required|`<button>`|
|Name 'About' is conveyed|required|Visible text content contained within the `<button>` element|
|State of the button (collapsed) is conveyed|required|`aria-expanded="false"`|

#### Read information about a collapsed disclosure button in interaction mode

* Applies to: JAWS, NVDA
* Mode: interaction
* Instructions: With focus on the first disclosure button in the navigation region, read information about the button.
* Commands:
    * Insert+Tab
* Setup script description: sets focus on the first disclosure button

##### Assertions

|Assertion|Priority|Reference|
|---------|--------|-----|
|Role 'button' is conveyed|required|`<button>`|
|Name 'About' is conveyed|required|Visible text content contained within the `<button>` element|
|State of the button (collapsed) is conveyed|required|`aria-expanded="false"`|

#### Read information about a collapsed disclosure button

* Applies to: macOS VoiceOver
* Mode: interaction
* Instructions: With focus on the first disclosure button in the navigation region, read information about the button.
* Commands:
    * Control+Option+F3
    * Control+Option+F4
* Setup script description: sets focus on the first disclosure button

##### Assertions

|Assertion|Priority|Reference|
|---------|--------|-----|
|Role 'button' is conveyed|required|`<button>`|
|Name 'About' is conveyed|required|Visible text content contained within the `<button>` element|
|State of the button (collapsed) is conveyed|required|`aria-expanded="false"`|

#### Read information about an expanded disclosure button in reading mode

* Applies to: JAWS, NVDA
* Mode: reading
* Instructions: With the reading cursor on the first disclosure button in the navigation region, read information about the button.
* Commands:
    * Insert+Tab
* Setup script description: sets focus on the first disclosure button, and sets its state to expanded

##### Assertions

|Assertion|Priority|Reference|
|---------|--------|-----|
|Role 'button' is conveyed|required|`<button>`|
|Name 'About' is conveyed|required|Visible text content contained within the `<button>` element|
|State of the button (expanded) is conveyed|required|`aria-expanded="true"`|

#### Read information about an expanded disclosure button in interaction mode

* Applies to: JAWS, NVDA
* Mode: interaction
* Instructions: With focus on the first disclosure button in the navigation region, read information about the button.
* Commands:
    * Insert+Tab
* Setup script description: sets focus on the first disclosure button, and sets its state to expanded

##### Assertions

|Assertion|Priority|Reference|
|---------|--------|-----|
|Role 'button' is conveyed|required|`<button>`|
|Name 'About' is conveyed|required|Visible text content contained within the `<button>` element|
|State of the button (expanded) is conveyed|required|`aria-expanded="true"`|

#### Read information about an expanded disclosure button

* Applies to: macOS VoiceOver
* Mode: interaction
* Instructions: With focus on the first disclosure button in the navigation region, read information about the button.
* Commands:
    * Control+Option+F3
    * Control+Option+F4
* Setup script description: sets focus on the first disclosure button, and sets its state to expanded

##### Assertions

|Assertion|Priority|Reference|
|---------|--------|-----|
|Role 'button' is conveyed|required|`<button>`|
|Name 'About' is conveyed|required|Visible text content contained within the `<button>` element|
|State of the button (expanded) is conveyed|required|`aria-expanded="true"`|

#### Operate a collapsed disclosure button in reading mode

* Applies to: JAWS, NVDA
* Mode: reading
* Instructions: With the reading cursor on the first disclosure button in the navigation region, set the state of the button to expanded.
* Commands:
    * Space
    * Enter
* Setup script description: sets focus on the first disclosure button

##### Assertions

|Assertion|Priority|Reference|
|---------|--------|-----|
|Change in state (to expanded) is conveyed|required|`aria-expanded="true"`|

#### Operate a collapsed disclosure button in interaction mode

* Applies to: JAWS, NVDA
* Mode: interaction
* Instructions: With focus on the first disclosure button in the navigation region, set the state of the button to expanded.
* Commands:
    * Space
    * Enter
* Setup script description: sets focus on the first disclosure button

##### Assertions

|Assertion|Priority|Reference|
|---------|--------|-----|
|Change in state (to expanded) is conveyed|required|`aria-expanded="true"`|

#### Operate a collapsed disclosure button

* Applies to: macOS VoiceOver
* Mode: interaction
* Instructions: With focus on the first disclosure button in the navigation region, set the state of the button to expanded.
* Commands:
    * Control+Option+Space
    * Space
    * Enter
* Setup script description: sets focus on the first disclosure button

##### Assertions

|Assertion|Priority|Reference|
|---------|--------|-----|
|Change in state (to expanded) is conveyed|required|`aria-expanded="true"`|

#### Operate an expanded disclosure button in reading mode

* Applies to: JAWS, NVDA
* Mode: reading
* Instructions: With the reading cursor on the first disclosure button in the navigation region, set the state of the button to collapsed.
* Commands:
    * Space
    * Enter
* Setup script description: sets focus on the first disclosure button, and sets its state to expanded

##### Assertions

|Assertion|Priority|Reference|
|---------|--------|-----|
|Change in state (to collapsed) is conveyed|required|`aria-expanded="false"`|

#### Operate an expanded disclosure button in interaction mode

* Applies to: JAWS, NVDA
* Mode: interaction
* Instructions: With focus on the first disclosure button in the navigation region, set the state of the button to collapsed.
* Commands:
    * Space
    * Enter
* Setup script description: sets focus on the first disclosure button, and sets its state to expanded

##### Assertions

|Assertion|Priority|Reference|
|---------|--------|-----|
|Change in state (to collapsed) is conveyed|required|`aria-expanded="false"`|

#### Operate an expanded disclosure button

* Applies to: macOS VoiceOver
* Mode: interaction
* Instructions: With focus on the first disclosure button in the navigation region, set the state of the button to collapsed.
* Commands:
    * Control+Option+Space
    * Space
    * Enter
* Setup script description: sets focus on the first disclosure button, and sets its state to expanded

##### Assertions

|Assertion|Priority|Reference|
|---------|--------|-----|
|Change in state (to collapsed) is conveyed|required|`aria-expanded="false"`|

#### Navigate from an expanded disclosure button to a link in the associated dropdown in reading mode

* Applies to: JAWS, NVDA
* Mode: reading
* Instructions: With the reading cursor on the first disclosure button in the navigation region, move into the button's associated list of links.
* Commands:
    * Tab
    * Down Arrow
* Setup script description: sets focus on the first disclosure button, and sets its state to expanded

##### Assertions

|Assertion|Priority|Reference|
|---------|--------|-----|
|Role of the dropdown ('list') is conveyed|required|`<ul>`|
|Number of items in the dropdown (4) is conveyed|required|calculated|
|Role of the first item in the dropdown ('link') is conveyed|required|`<a>`|
|Name of the first item in the dropdown ('Overview') is conveyed|required|Visible text content contained within the `<a>` element|

#### Navigate from an expanded disclosure button to a link in the associated dropdown in interaction mode

* Applies to: JAWS, NVDA
* Mode: interaction
* Instructions: With focus on the first disclosure button in the navigation region, move into the button's associated list of links.
* Commands:
    * Tab
    * Down Arrow
* Setup script description: sets focus on the first disclosure button, and sets its state to expanded.

##### Assertions

|Assertion|Priority|Reference|
|---------|--------|-----|
|Role of the dropdown ('list') is conveyed|required|`<ul>`|
|Number of items in the dropdown (4) is conveyed|required|calculated|
|Role of the first item in the dropdown ('link') is conveyed|required|`<a>`|
|Name of the first item in the dropdown ('Overview') is conveyed|required|Visible text content contained within the `<a>` element|

#### Navigate from an expanded disclosure button to a link in the associated dropdown

* Applies to: macOS VoiceOver
* Mode: interaction
* Instructions: With focus on the first disclosure button in the navigation region, move into the button's associated list of links.
* Commands:
    * Control+Option+Right Arrow
    * Tab
    * Down Arrow
* Setup script description: sets focus on the first disclosure button, and sets its state to expanded.

##### Assertions

|Assertion|Priority|Reference|
|---------|--------|-----|
|Role of the dropdown ('list') is conveyed|required|`<ul>`|
|Number of items in the dropdown (4) is conveyed|required|calculated|
|Role of the first item in the dropdown ('link') is conveyed|required|`<a>`|
|Name of the first item in the dropdown ('Overview') is conveyed|required|Visible text content contained within the `<a>` element|

#### Navigate from an expanded disclosure button to the current page link in reading mode

* Applies to: JAWS, NVDA
* Mode: reading
* Instructions: With the reading cursor on the first disclosure button in the navigation region, move into the button's associated list of links.
* Commands:
    * Tab
    * Down Arrow
* Setup script description: sets focus on the first disclosure button, sets its state to expanded, and marks the first link in the associated dropdown as being the current page

##### Assertions

|Assertion|Priority|Reference|
|---------|--------|-----|
|Role of the dropdown ('list') is conveyed|required|`<ul>`|
|Number of items in the dropdown (4) is conveyed|required|calculated|
|Role of the first item in the dropdown ('link') is conveyed|required|`<a>`|
|Name of the first item in the dropdown ('Overview') is conveyed|required|Visible text content contained within the `<a>` element|
|State of the first item in the dropdown (as the current page) is conveyed|required|`aria-current="page"`|

#### Navigate from an expanded disclosure button to the current page link in interaction mode

* Applies to: JAWS, NVDA
* Mode: interaction
* Instructions: With focus on the first disclosure button in the navigation region, move into the button's associated list of links.
* Commands:
    * Tab
    * Down Arrow
* Setup script description: sets focus on the first disclosure button, sets its state to expanded, and marks the first link in the associated dropdown as being the current page

##### Assertions

|Assertion|Priority|Reference|
|---------|--------|-----|
|Role of the dropdown ('list') is conveyed|required|`<ul>`|
|Number of items in the dropdown (4) is conveyed|required|calculated|
|Role of the first item in the dropdown ('link') is conveyed|required|`<a>`|
|Name of the first item in the dropdown ('Overview') is conveyed|required|Visible text content contained within the `<a>` element|
|State of the first item in the dropdown (as the current page) is conveyed|required|`aria-current="page"`|

#### Navigate from an expanded disclosure button to the current page link

* Applies to: macOS VoiceOver
* Mode: interaction
* Instructions: With focus on the first disclosure button in the navigation region, move into the button's associated list of links.
* Commands:
    * Control+Option+Right Arrow
    * Tab
    * Down Arrow
* Setup script description: sets focus on the first disclosure button, sets its state to expanded, and marks the first link in the associated dropdown as being the current page

##### Assertions

|Assertion|Priority|Reference|
|---------|--------|-----|
|Role of the dropdown ('list') is conveyed|required|`<ul>`|
|Number of items in the dropdown (4) is conveyed|required|calculated|
|Role of the first item in the dropdown ('link') is conveyed|required|`<a>`|
|Name of the first item in the dropdown ('Overview') is conveyed|required|Visible text content contained within the `<a>` element|
|State of the first item in the dropdown (as the current page) is conveyed|required|`aria-current="page"`|

#### Navigate from a dropdown to a collapsed disclosure button in reading mode

* Applies to: JAWS, NVDA
* Mode: reading
* Instructions: With the reading cursor on a link in the first dropdown, close the dropdown and return focus to the associated disclosure button.
* Commands:
    * Escape
* Setup script description: sets the state of the first disclosure button to expanded, and sets focus on the first link of the associated dropdown

##### Assertions

|Assertion|Priority|Reference|
|---------|--------|-----|
|Role 'button' is conveyed|required|`<button>`|
|Name 'About' is conveyed|required|Visible text content contained within the `<button>` element|
|State of the button (collapsed) is conveyed|required|`aria-expanded="false"`|

#### Navigate from a dropdown to a collapsed disclosure button in interaction mode

* Applies to: JAWS, NVDA
* Mode: interaction
* Instructions: With focus on a link in the first dropdown, close the dropdown and return focus to the associated disclosure button.
* Commands:
    * Escape
* Setup script description: sets the state of the first disclosure button to expanded, and sets focus on the first link of the associated dropdown

##### Assertions

|Assertion|Priority|Reference|
|---------|--------|-----|
|Role 'button' is conveyed|required|`<button>`|
|Name 'About' is conveyed|required|Visible text content contained within the `<button>` element|
|State of the button (collapsed) is conveyed|required|`aria-expanded="false"`|

#### Navigate from a dropdown to a collapsed disclosure button

* Applies to: macOS VoiceOver
* Mode: interaction
* Instructions: With focus on a link in the first dropdown, close the dropdown and return focus to the associated disclosure button.
* Commands:
    * Escape
* Setup script description: sets the state of the first disclosure button to expanded, and sets focus on the first link of the associated dropdown

##### Assertions

|Assertion|Priority|Reference|
|---------|--------|-----|
|Role 'button' is conveyed|required|`<button>`|
|Name 'About' is conveyed|required|Visible text content contained within the `<button>` element|
|State of the button (collapsed) is conveyed|required|`aria-expanded="false"`|

#### Navigate forwards to a link in a dropdown in reading mode

* Applies to: JAWS
* Mode: reading
* Instructions: With the reading cursor on a link in the first dropdown, navigate to the next link.
* Commands:
    * U
    * Down Arrow
    * Tab
* Setup script description: sets the state of the first disclosure button to expanded, and sets focus on the first link of the associated dropdown

##### Assertions

|Assertion|Priority|Reference|
|---------|--------|-----|
|Role 'link' is conveyed|required|`<a>`|
|Name 'Administration' is conveyed|required|Visible text content contained within the `<a>` element|

#### Navigate forwards to a link in a dropdown in reading mode

* Applies to: NVDA
* Mode: reading
* Instructions: With the reading cursor on a link in the first dropdown, navigate to the next link.
* Commands:
    * U
    * K
    * Down Arrow
    * Tab
* Setup script description: sets the state of the first disclosure button to expanded, and sets focus on the first link of the associated dropdown

##### Assertions

|Assertion|Priority|Reference|
|---------|--------|-----|
|Role 'link' is conveyed|required|`<a>`|
|Name 'Administration' is conveyed|required|Visible text content contained within the `<a>` element|

#### Navigate forwards to a link in a dropdown in interaction mode

* Applies to: JAWS, NVDA
* Mode: interaction
* Instructions: With focus on a link in the first dropdown, navigate to the next link.
* Commands:
    * Down Arrow
    * Right Arrow
    * Tab
* Setup script description: sets the state of the first disclosure button to expanded, and sets focus on the first link of the associated dropdown

##### Assertions

|Assertion|Priority|Reference|
|---------|--------|-----|
|Role 'link' is conveyed|required|`<a>`|
|Name 'Administration' is conveyed|required|Visible text content contained within the `<a>` element|

#### Navigate forwards to a link in a dropdown

* Applies to: macOS VoiceOver
* Mode: interaction
* Instructions: With focus on a link in the first dropdown, navigate to the next link.
* Commands:
    * Control+Option+Right Arrow
    * Down Arrow
    * Right Arrow
    * Tab
* Setup script description: sets the state of the first disclosure button to expanded, and sets focus on the first link of the associated dropdown

##### Assertions

|Assertion|Priority|Reference|
|---------|--------|-----|
|Role 'link' is conveyed|required|`<a>`|
|Name 'Administration' is conveyed|required|Visible text content contained within the `<a>` element|

#### Navigate backwards to a link in a dropdown in reading mode

* Applies to: JAWS
* Mode: reading
* Instructions: With the reading cursor on a link in the first dropdown, navigate to the previous link.
* Commands:
    * Shift+U
    * Up Arrow
    * Shift+Tab
* Setup script description: sets the state of the first disclosure button to expanded, and sets focus on the second link of the associated dropdown

##### Assertions

|Assertion|Priority|Reference|
|---------|--------|-----|
|Role 'link' is conveyed|required|`<a>`|
|Name 'Overview' is conveyed|required|Visible text content contained within the `<a>` element|

#### Navigate backwards to a link in a dropdown in reading mode

* Applies to: NVDA
* Mode: reading
* Instructions: With the reading cursor on a link in the first dropdown, navigate to the previous link.
* Commands:
    * Shift+U
    * Shift+K
    * Up Arrow
    * Shift+Tab
* Setup script description: sets the state of the first disclosure button to expanded, and sets focus on the second link of the associated dropdown

##### Assertions

|Assertion|Priority|Reference|
|---------|--------|-----|
|Role 'link' is conveyed|required|`<a>`|
|Name 'Overview' is conveyed|required|Visible text content contained within the `<a>` element|

#### Navigate backwards to a link in a dropdown in interaction mode

* Applies to: JAWS, NVDA
* Mode: interaction
* Instructions: With focus on a link in the first dropdown, navigate to the previous link.
* Commands:
    * Up Arrow
    * Left Arrow
    * Shift+Tab
* Setup script description: sets the state of the first disclosure button to expanded, and sets focus on the second link of the associated dropdown

##### Assertions

|Assertion|Priority|Reference|
|---------|--------|-----|
|Role 'link' is conveyed|required|`<a>`|
|Name 'Overview' is conveyed|required|Visible text content contained within the `<a>` element|

#### Navigate backwards to a link in a dropdown

* Applies to: macOS VoiceOver
* Mode: interaction
* Instructions: With focus on a link in the first dropdown, navigate to the previous link.
* Commands:
    * Control+Option+Left Arrow
    * Up Arrow
    * Left Arrow
    * Shift+Tab
* Setup script description: sets the state of the first disclosure button to expanded, and sets focus on the second link of the associated dropdown

##### Assertions

|Assertion|Priority|Reference|
|---------|--------|-----|
|Role 'link' is conveyed|required|`<a>`|
|Name 'Overview' is conveyed|required|Visible text content contained within the `<a>` element|

#### Navigate to the first link in a dropdown in interaction mode

* Applies to: JAWS, NVDA
* Mode: interaction
* Instructions: With focus on a link in the first dropdown, navigate to the first link.
* Commands:
    * Home
* Setup script description: sets the state of the first disclosure button to expanded, and sets focus on the second link of the associated dropdown

##### Assertions

|Assertion|Priority|Reference|
|---------|--------|-----|
|Role 'link' is conveyed|required|`<a>`|
|Name 'Overview' is conveyed|required|Visible text content contained within the `<a>` element|

#### Navigate to the first link in a dropdown

* Applies to: macOS VoiceOver
* Mode: interaction
* Instructions: With focus on a link in the first dropdown, navigate to the first link.
* Commands:
    * Home
* Setup script description: sets the state of the first disclosure button to expanded, and sets focus on the second link of the associated dropdown

##### Assertions

|Assertion|Priority|Reference|
|---------|--------|-----|
|Role 'link' is conveyed|required|`<a>`|
|Name 'Overview' is conveyed|required|Visible text content contained within the `<a>` element|

#### Navigate to the last link in a dropdown in interaction mode

* Applies to: JAWS, NVDA
* Mode: interaction
* Instructions: With focus on a link in the first dropdown, navigate to the last link.
* Commands:
    * End
* Setup script description: sets the state of the first disclosure button to expanded, and sets focus on the first link of the associated dropdown

##### Assertions

|Assertion|Priority|Reference|
|---------|--------|-----|
|Role 'link' is conveyed|required|`<a>`|
|Name 'Campus Tours' is conveyed|required|Visible text content contained within the `<a>` element|

#### Navigate to the last link in a dropdown

* Applies to: macOS VoiceOver
* Mode: interaction
* Instructions: With focus on a link in the first dropdown, navigate to the last link.
* Commands:
    * End
* Setup script description: sets the state of the first disclosure button to expanded, and sets focus on the first link of the associated dropdown

##### Assertions

|Assertion|Priority|Reference|
|---------|--------|-----|
|Role 'link' is conveyed|required|`<a>`|
|Name 'Campus Tours' is conveyed|required|Visible text content contained within the `<a>` element|

#### Activate a link in a dropdown in reading mode

* Applies to: JAWS, NVDA
* Mode: reading
* Instructions: With the reading cursor on a link in the first dropdown, activate the link.
* Commands:
    * Enter
    * Space
* Setup script description: sets the state of the first disclosure button to expanded, and sets focus on the first link of the associated dropdown

##### Assertions

|Assertion|Priority|Reference|
|---------|--------|-----|
|Role 'Region' is conveyed|required|`role="region"`|
|Name 'Mythical University sample page content' is conveyed|required|`aria-label`|

#### Activate a link in a dropdown in interaction mode

* Applies to: JAWS, NVDA
* Mode: interaction
* Instructions: With focus on a link in the first dropdown, activate the link.
* Commands:
    * Enter
    * Space
* Setup script description: sets the state of the first disclosure button to expanded, and sets focus on the first link of the associated dropdown

##### Assertions

|Assertion|Priority|Reference|
|---------|--------|-----|
|Role 'Region' is conveyed|required|`role="region"`|
|Name 'Mythical University sample page content' is conveyed|required|`aria-label`|

#### Activate a link in a dropdown

* Applies to: macOS VoiceOver
* Mode: interaction
* Instructions: With focus on a link in the first dropdown, activate the link.
* Commands:
    * Control+Option+Space
    * Enter
    * Space
* Setup script description: sets the state of the first disclosure button to expanded, and sets focus on the first link of the associated dropdown

##### Assertions

|Assertion|Priority|Reference|
|---------|--------|-----|
|Role 'Region' is conveyed|required|`role="region"`|
|Name 'Mythical University sample page content' is conveyed|required|`aria-label`|

**Comment by jscholes** [comment]
These tests are ready for review. For convenience, I've added links to the previewable index and review pages in the initial comment.

* [Previewable Tests Index](https://raw.githack.com/w3c/aria-at/tests/disclosure-navigation/tests/disclosure-navigation/index.html)
* [Previewable Tests Review Page](https://raw.githack.com/w3c/aria-at/tests/disclosure-navigation/review/disclosure-navigation.html)
