### ISSUE TITLE
Re-number tests when filtering by AT on review pages

### ISSUE THREAD

**Issue by jscholes** [w3c/aria-at#587]
Review pages, e.g. https://w3c.github.io/aria-at/build/review/breadcrumb.html, allow readers to filter the displayed tests by AT, for instance to only see tests applicable to JAWS.  However, the tests are not re-numbered when this filtering occurs.  On the linked example, checking the "JAWS" radio button creates a gap between tests 4 and 7.

This is problematic if using the review pages in conjunction with consultation of the same tests within the ARIA-AT App, such as when working with someone trying to resolve test conflicts.  In the context of the app, tests are numbered (with 1-based indexing) consecutively within the context of the AT/browser combination being tested.  So for Breadcrumb, test `#7` on the review page would actually be test `#5` for the user of the app targeting JAWS.  This makes it more difficult for both people to ensure that they're looking at the same test, as they can only rely on test titles which are more wordy and often similar to each other.

**Comment by SamuelHShaw** [comment]
@s3ththompson Hi, just checking in from PAC to see if there are any updates on this, and possibly an ETA on when it may be able to be addressed?

**Comment by s3ththompson** [comment]
Hi @SamuelHShaw, as mentioned on the other thread the Bocoup office was closed last week for an all-hands. We're working through these issues as we can get to them since we're currently in the middle of the Q1 2022 planning process.

This issue should be relatively straightforward. Agreed this is a problematic issue since it throws off numbering when comparing between the App and the source files!
