### ISSUE TITLE
Commit hash missing from review page

### ISSUE THREAD

**Issue by jscholes** [w3c/aria-at#597]
On the [Test Patterns for Review](https://w3c.github.io/aria-at/build/) page, the "Commit of Last Change" column only contains the word "commit" for the most recent commit on the most recently modified (or merged?) test plan row.  For example, at the time of writing, the most recently merged pattern is "seek-slider", and all test plans other than that one show a commit hash as expected.  Note that this info will become out of date as additional plans are modified and merged into master; look for the row with the word "commit" instead of a hash.

This also impacts pull requests.  For instance, here's the review page for PR https://github.com/w3c/aria-at/pull/545:

https://raw.githack.com/w3c/aria-at/tests/banner/build/index.html

As you'd expect, the most recently modified test plan on that branch is "banner", and the "banner" row only has the word "commit" in the last column instead of a hash.  I'll leave that branch in place, rather than deleting it, to serve as an example for this issue.

CC @s3ththompson

**Comment by SamuelHShaw** [comment]
@s3ththompson  Hi, just checking in from PAC to see if there are any updates on this, and possibly an ETA on when it may be able to be addressed?

**Comment by s3ththompson** [comment]
Hi @SamuelHShaw, thanks for filing this issue! The Bocoup office was closed last week for an all-hands. We're working through these issues as we can get to them since we're currently in the middle of the Q1 2022 planning process. My understanding is that we'll have a PAC / Bocoup partner meeting soon to discuss how we can best work together and provide timely ETAs for support issues going forward.
