### ISSUE TITLE
Conflicting results for test 17 "Open a collapsed select-only combobox to the last option in interaction mode" (Select Only Combobox Example)

### ISSUE THREAD

**Issue by jongund** [w3c/aria-at#639]
## Description of Behavior

Is "not selected" suppose to be explicitly announced, it seems that this would be overly verbose, since most items in the list re typically not selected.  

## Test Setup

- Test File at Exact Commit: [test-17-open-collapsed-select-only-combobox-to-last-option-interaction-nvda.collected.html](https://aria-at.w3.org/aria-at/091420a186f267d6ed8f581dc0e8e168d194e709/build/tests/combobox-select-only/test-17-open-collapsed-select-only-combobox-to-last-option-interaction-nvda.collected.html)
- AT: NVDA (version Latest)
- Browser: Firefox (version Latest)

## Review Conflicts for "Open a collapsed select-only combobox to the last option in interaction mode"

1.  ### Assertion Results for "End" Command and "Role of the popup ('listbox') is conveyed" Assertion
    
    *   Tester jha11y recorded output "expanded Favorite Fruit list Huckleberry not selected 13 of 13" and marked assertion as failing with incorrect output.
    *   Tester jongund recorded output "expanded Favorite Fruit list Huckleberry not selected 13 of 13 " and marked assertion as passing.

**Comment by jscholes** [comment]
I agree that this example causes overly verbose speech, because of each item being reported as "not selected".  But, that is down to how the example is coded, to explicitly divert from the behaviour of a standard `<select>` on Windows where selection usually follows focus.  To fix that, if indeed it is seen as a flaw, the example would need to be modified.  The screen reader should convey "not selected" state, because it has no idea about whether that state is or is not relevant to the user for any particular widget.

**Comment by jha11y** [comment]
so the assertion says that not selected state is announced which it is, so I'm confused as how this can be failing.  It may be overly verbose, but the output matches the assertion.  Am I missing something?

**Comment by jongund** [comment]
This issue also has the reverse issue of saying "selected", when selection follows focus this could be annoying.  The current test plan requires some tests, for example #8, to announce "selected", but NVDA is not announcing it.
