### ISSUE TITLE
Inconsistency of instructions on "Navigate from an expanded disclosure button to the current page link in interaction mode" (Disclosure Navigation Menu Example, Test 20)

### ISSUE THREAD

**Issue by AlyssaGourley** [w3c/aria-at#651]
There are conflicting instructions for this test, which previously caused a conflict of results. The test description says, "Navigate from an expanded disclosure button to the current page link in interaction mode." However, under the "Test Instructions" heading, the instruction for step 3 is as follows:
"If NVDA did not make the focus mode sound when the test page loaded, press Insert+Space to turn focus mode on."
Therefore, when I originally completed the test, I did so in focus mode, resulting in the conflict. I have since reran the test in the correct mode and modified my results.

## Test Setup

- Test File at Exact Commit: [test-29-navigate-from-expanded-disclosure-button-to-current-page-link-interaction-nvda.collected.html](https://aria-at.w3.org/aria-at/4ed847af15a026c816f2841c1a15d32d466f0b1f/build/tests/disclosure-navigation/test-29-navigate-from-expanded-disclosure-button-to-current-page-link-interaction-nvda.collected.html)
- AT: NVDA (version Latest)
- Browser: Firefox (version Latest)

## Review Conflicts for "Navigate from an expanded disclosure button to the current page link in interaction mode"

1.  ### Assertion Results for "Tab" Command and "Number of items in the dropdown (4) is conveyed" Assertion
    
    *   Tester AlyssaGourley recorded output "list Overview link" and marked assertion as failing with no output.
    *   Tester louis4533 recorded output "list with 4 items Overview link current page" and marked assertion as passing.
2.  ### Assertion Results for "Tab" Command and "State of the first item in the dropdown (as the current page) is conveyed" Assertion
    
    *   Tester AlyssaGourley recorded output "list Overview link" and marked assertion as failing with no output.
    *   Tester louis4533 recorded output "list with 4 items Overview link current page" and marked assertion as passing.
3.  ### Assertion Results for "Down Arrow" Command and "Number of items in the dropdown (4) is conveyed" Assertion
    
    *   Tester AlyssaGourley recorded output "list Overview link" and marked assertion as failing with no output.
    *   Tester louis4533 recorded output "list with 4 items link current page Overview" and marked assertion as passing.
4.  ### Assertion Results for "Down Arrow" Command and "State of the first item in the dropdown (as the current page) is conveyed" Assertion
    
    *   Tester AlyssaGourley recorded output "list Overview link" and marked assertion as failing with no output.
    *   Tester louis4533 recorded output "list with 4 items link current page Overview" and marked assertion as passing.

**Comment by jscholes** [comment]
@AlyssaGourley Thanks for the feedback!  However, I don't understand the conflict within the instructions that you've highlighted.

The test title indicates that the test should be carried out in "interaction mode".  Within the ARIA-AT project, "interaction mode" is an abstract term, refering either to Forms Mode within JAWS or Focus Mode in NVDA.  So, when the instructions later ask you to "turn focus mode on", they are in sync with the intent of the test as conveyed by the title; Focus Mode must be enabled so that the test can be carried out in interaction mode.

Please let me know if I'm misunderstanding your concern here, or if you feel that something about this setup can be made clearer.  Do you feel that the distinction between "interaction mode" and "focus mode" can cause confusion?  When you re-executed the test, did you use Focus Mode, or Browse Mode?  Browse Mode is referenced as "reading mode" within ARIA-AT tests.

**Comment by AlyssaGourley** [comment]
Hi James, 
Thanks for the explanation. I now understand why the same mode is being referenced in two different ways "interaction" and "Focus." I have completed the test in "focus mode" and cleared the conflicts.
Thanks,
Alyssa
