### ISSUE TITLE
Feedback: "Navigate to the beginning of a modal dialog in reading mode" (Modal Dialog Example, Test 14)

### ISSUE THREAD

**Issue by IsaDC** [w3c/aria-at#731]
## Description of Behavior

There are two issues while running this test:
1.	Having to change JAWS cursor.
2.	JAWS reading landmarks.

## Test Setup

- Test File at Exact Commit: [test-14-navigate-to-the-beginning-of-a-modal-dialog-reading-jaws.collected.html](https://aria-at.w3.org/aria-at/58d4196e8e839673d82de218943cf1e165216a3b/build/tests/modal-dialog/test-14-navigate-to-the-beginning-of-a-modal-dialog-reading-jaws.collected.html)
- AT: JAWS (version Latest)
- Browser: Chrome (version Latest)

## Review Conflicts for "Navigate to the beginning of a modal dialog in reading mode"

1.  ### Unexpected Behaviors for "Control+Home, then Down Arrow" Command
    
    *   Tester IsaDC recorded output "Modal Dialog Example main region" and noted "I had to get JAWS out of formes mode and then press the commands. However, JAWS needs 2 down arrow to land on the heading.".
    *   Tester louis4533 recorded output "main region" and noted "Forms mode was automatically activated with focus placed on the Street: edit field. I had to press escape in order to exit forms mode before being able to type the testing key sequence (Control+Home, then Down Arrow).".

**Comment by jscholes** [comment]
1. Update the test to remove Down Arrow from the commands, leaving only Ctrl+Home.  If a modal dialog is open, JAWS should not read the page title as the first line of the virtual buffer.
2. After that, the existing test results should be updated to indicate a failure to meet the relevant assertions, given that the page title is spoken rather than the heading.  The indications of undesirable behaviours should also be removed.
3. The instructions informing users how to exit Forms Mode must be updated to reference Escape, rather than Insert+Z, and the Alt+Delete instruction should be removed.  Note that:
    * This only impacts the instructions for exiting Forms Mode, and not entering it.  However, @mcking65 raised some concerns about continuing to use Insert+Z to enter Forms Mode, given that it will disable the Virtual PC Cursor completely.  If a tester is then instructed to, for instance, move focus to an element which should trigger the Virtual PC Cursor again, this will not happen.
    * This change must be made within the test renderer, not within each test or test plan.  CC @richnoah; let me know if you need additional info.
5. Tests relating to closing a modal dialog must be updated to require two presses of Escape, instead of one: the first will turn off Forms Mode, and the second will close the dialog.  Note that:
    * this will require tests to be re-run; and
    * the same change should also be made for NVDA, i.e. the first press of Escape will exit Focus Mode which is expected.

Note: updating the test commands, to remove Down Arrow, will also remove any indication of the incorrect main region announcement.

**Comment by richnoah** [comment]
@jscholes the current text in the instructions for Jaws reads "Verify the Virtual Cursor is active by pressing Alt+Delete.  If it is not, turn on the Virtual Cursor by pressing Insert+Z.

Should this be updated to read "Verify the Virtual Cursor is active by pressing Escape."

**Comment by jscholes** [comment]
@richnoah I'd suggest:

> Verify the Virtual Cursor is active by pressing Alt+Delete. If it is not, exit Forms Mode to activate the Virtual Cursor by pressing Escape.

**Comment by IsaDC** [comment]
Conflicts will be addressed by re-running tests.

**Comment by jscholes** [comment]
@richnoah Do you have an ETA for this change?
