### ISSUE TITLE
Page load time on ARIA-AT App Reports page

### ISSUE THREAD

**Issue by cookiecrook** [w3c/aria-at#827]
Ongoing reliability problems on reports site (502 HTTP errors, JSON parsing errors, other timeouts, and overall slow performance) make it challenging to review and diagnose the example pages and report results.

### Reproduction Steps
1. Load https://aria-at.w3.org/reports in browser of choice.
2. Cmd+Click on Mac (Ctrl+Click on Windows?) all 9 examples to open them in background tabs.

### Results
**Problem 1:** all pages are very slow loading, including the ones that complete successfully.
**Problem 2:** The first 6 background example tabs result in a JSON error: `JSON Parse error: Unrecognized token '<'`
**Problem 3:** The final 3 tabs result in an HTTP error: `502 Bad Gateway nginx/1.18.0`

### Notes
These steps are 100% reproducible for me in any browser on Mac. I assume this is a server load response problem, but 9 page requests at any frequency shouldn't result in a DoS-like response from the server. It breaks the XHR requests in addition to subsequent page loads.

Happy to provide more info if needed.

**Comment by cookiecrook** [comment]
FWIW, I'm very appreciative of the efforts to raise these SR consistency problems to everyone's attention. 

Pointing this bug out primarily because it slows the engineering response and diagnostic time of a variety of stakeholders.... Costing the engineering attention that will be pointed elsewhere in the meantime.

**Comment by s3ththompson** [comment]
Hi James, thanks for reproducing and reporting this issue. We're working on diagnosing the issue now.

So far, we've identified a Node.js out-of-memory error. I'll share more here when we have a better sense of the timeline for getting this resolved. Thanks for your patience.

**Comment by s3ththompson** [comment]
@cookiecrook we just deployed a series of performance updates to the site and upgraded the server infrastructure. Please find the latest version at https://aria-at.w3.org/

Report page load times are now around 4-5s in our testing. I have not been able to reproduce any timeouts or errors after the updates. I am now able to open multiple pages in parallel again.

I'm going to keep this issue open because we can still improve performance further, but rename it to focus on reducing page load times. Please let us know if you run into any additional errors or reliability issues.

**Comment by cookiecrook** [comment]
@s3ththompson wrote:
> I'm going to keep this issue open because we can still improve performance further, but rename it to focus on reducing page load times. 

I can verify this bug as filed is resolved... Thanks!

Rather than repurposing it for general perf, I'd recommend closing it, but obviously it's your call. Cheers!

**Comment by mcking65** [comment]
Performance issues have been resolved; loads are subsecond now.
