### ISSUE TITLE
Feedback: "Trigger an alert in reading mode" (Alert Example, Test 1)

### ISSUE THREAD

**Issue by RFischer-FS** [w3c/aria-at#840]
## Description of Behavior

We had the suggested behavior implemented a while ago and learned that this isn't beneficial for our users. We have two issues with announcing the alert role:
1) Many web pages use too many alerts on their pages. And in addition to a load of alerts, the user would hear the extra word "alert" continuously, 
2) Many times, the test of the alert is short, as you also present in your example with the word "Hello". Therefore adding the word alert makes the actual me alert unnecessarily long, without a clear benefit.

Due to these two reasons, we don't announce the alert role and don't plan on turning it back on.  

## Test Setup

- Test File: [test-01-trigger-alert-reading-jaws.collected.html](https://aria-at.netlify.app/tests/alert/test-01-trigger-alert-reading-jaws.collected.html)
- AT: JAWS (version undefined)
- Browser: Chrome (version undefined)

**Comment by jscholes** [comment]
@RFischer-FS Thank you so much for the detailed feedback, and particularly for raising this in the context of reactions from JAWS users.

The Community Group discussed this during the meeting of November 3, 2022, and reached consensus on changing the priority of the following assertion from required to optional:

> Role 'alert' is conveyed

With such a change in place, the data would still indicate that JAWS does not announce the role, but purely as a factual statement, with a relatively lower level of importance than at present.

@RFischer-FS Do you feel that this change would address your concerns with the test?  We're more than happy to facilitate continued discussion, via either this issue thread, a future CG meeting, or our upcoming call on November 17.

Thanks again!

**Comment by mfairchild365** [comment]
Just as a note: it occurred to me that I do remember hearing JAWS convey the alert role, but I couldn't place the circumstances. It turns out that JAWS + Firefox does in fact convey the alert role by stating the word "alert" prior to the rest of the announcement. Some other combinations that convey the alert role include NVDA + Firefox, and potentially VO+Safari on MacOS. VO+Safari on MacOS uses an earcon for role=alert, which is the same earcon it uses for aria-live=assertive (the earcon is not conveyed with aria-live=polite).

Just wanted to share these findings. If nothing else, I think it helps to support the desire to mark this assertion as optional and document which combinations do support it.

**Comment by jscholes** [comment]
@IsaDC Update from a meeting with Vispero on November 17, 2022: we are good to go on changing the priority of the role-related assertion to optional.

**Comment by IsaDC** [comment]
Role 'Alert' has been updated to optional.
